### ISSUE TITLE
False positive about not assigning variables

### ISSUE THREAD

**Issue by mwild1** [hishamhm/tl#55]
Not really sure I understand this issue, but I reduced it to a reasonable test case.

I was checking some real-world Lua code for which some require()d modules have type definitions, but I isolated this particular error to the Lua code only.

Code:

```lua
local methods = {};

function methods:method1()
        return { data = function () return 1, 2, 3 end }
end

function methods:method2()
        local one, two, three
        one, two, three = self:method1():data();
        return one, two, three
end

local a = setmetatable({}, { __index = methods });

print(a:method2())
```

Output of tl check:

```
========================================
2 errors:
t6.lua:9:7: variable is not being assigned a value
t6.lua:9:12: variable is not being assigned a value
========================================
4 unknown variables:
t6.lua:8:8: one
t6.lua:8:8: two
t6.lua:8:8: three
t6.lua:15:7: a.method2
```

The assignment is clearly happening (the script prints 1, 2, 3), so I'm not sure what triggers the errors.

**Comment by mwild1** [comment]
Slightly modified test case that removes any metatable stuff and reduces the problematic line to a single bare function call:

```lua
function f1()
        return { data = function () return 1, 2, 3 end }
end

function f2()
        local one, two, three
        local data = f1().data;
        one, two, three = data()
        return one, two, three
end

print(f2())
```

**Comment by hishamhm** [comment]
Thanks for the report! I believe I know what's going on: it is not being
smart about multiple returns in non-annotated return types in functions. It
should make no assumptions about them. Shouldn't be hard to fix!

**Comment by hishamhm** [comment]
Fixed! Commit 85b46b3 has a write-up on the details. I've been mostly testing `tl` on `.tl` files where annotations everywhere are the norm, but I definitely want to make it more lenient when processing Lua files. Do keep the feedback coming! :)

**Comment by mwild1** [comment]
Thanks for the fix and the comprehensive explanation! I tried to figure out what was going on, but couldn't find exactly where the type information was being inferred from. Your explanation makes sense, and the diff suggests it would have taken me much longer to fix :)

**Comment by mwild1** [comment]
Hmm, I ran the fixed tl against the original code and it still errors.

This test case still fails:

```lua
local methods = {};

function methods:method1()
        return { data = function () return 1, 2, 3 end }
end

function methods:method2()
        local one, two, three
        one, two, three = self:method1():data();
        return one, two, three
end

local a = setmetatable({}, { __index = methods });

print(a:method2())
```

**Comment by mwild1** [comment]
It seems to be because the method makes the parameters known, it gets treated as `function(self):<unknown type>` whereas in the other non-method case the function is simply treated as `<unknown type>` (which is what the fix checks for).

I tried to add some code to detect if just the return value was unknown, and then treat that as VARARG_UNKNOWN instead. Not sure if that's the right tree to bark up, but no squirrels came down anyway. I'm not even sure the check_function_call is being called for the function call in question, but I'm still trying to figure out debugging tl (tips welcome!). I also wonder if perhaps this particular case would be better handled when the function is first parsed.

Another semi-related observation I'll dump here... should it always hold true that: `tl check foo.tl && tl gen foo.tl && tl check foo.lua` will pass? (the type-annotated version of this test case passes fine, but the generated .lua code does not). If tl-generated code should always pass, that seems like a potential avenue to explore for future testing.

Sorry for the rambling here, still trying to get to grips with the project :)

**Comment by hishamhm** [comment]
> Your explanation makes sense, and the diff suggests it would have taken me much longer to fix :)

The core of the fix is really https://github.com/hishamhm/tl/commit/85b46b31e6ca1126c74572d62d2f4593166ec52e#diff-6f460b3c8abab5d8b33f5f8eb93dbc0dR3835-R3837 — the rest were more like code cleanups.

> I tried to add some code to detect if just the return value was unknown, and then treat that as VARARG_UNKNOWN instead. 

This does sound like a reasonable for `lax` (.lua) mode!

> I also wonder if perhaps this particular case would be better handled when the function is first parsed.

The code currently generates some types while parsing and some while typechecking, but it only does the distinction about "strict" and "lax" mode when typechecking. It might be that the parser is being too strict...

> should it always hold true that: `tl check foo.tl && tl gen foo.tl && tl check foo.lua` will pass?

**Great** question. At first I was going to say "no"... but upon thinking more, the right answer for this might be a "generally, yes", if lax mode is supposed to be really lax and never report an error if it can't prove for a fact that something is wrong. I wouldn't say a "hard yes" just yet because there might be really dynamic Lua situations that you can make tl accept by using a cast, that could still confuse tl when all types and casts are erased.

tl is still currently producing lots of `error` reports in unannotated Lua code which it should probably just mark as `unknown` only. I've been mostly focusing on strict mode so far, but I should give lax mode more love as I start to gradually type the LuaRocks codebase, which is my next project.
